env:
  browser: true
  es2020: true
  jquery: true
extends:
  - 'plugin:react/recommended'
  - standard
parser:
  "babel-eslint"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
plugins:
  - react
rules: {
  react/prop-types: "off",
  camelcase: "off"
}
globals: {
  App: "readable"
}
