version: 2.1
orbs:
  ruby: circleci/ruby@1.1.1
  node: circleci/node@4.0.0

jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.4-node
        environment:
          - DATABASE_URL=postgres://ubuntu:@127.0.0.1:5432/share_harder_test
      - image: circleci/postgres:10.13
        environment:
          - POSTGRES_USER=ubuntu
          - POSTGRES_DB=share_harder_test
          - POSTGRES_HOST_AUTH_METHOD=trust
      - image: circleci/redis:4.0.14
    executor: ruby/default
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Database Setup
          command: bundle exec rake db:schema:load
      - ruby/rubocop-check
      - ruby/rspec-test
      - run:
          name: ESLint
          command: yarn lint
